#!/bin/zsh
case $(sudo openvpn3 sessions-list) in
	"No sessions available")
		echo "Fuck"
	;; 
	*) 
		(
			for i in $(sudo openvpn3 sessions-list | grep .ovpn | awk -F ' ' '{print $3}') 
				sudo openvpn3 session-manage --disconnect --config $i
		)
		echo "All sessions disconnected"
		;;
esac