#! /bin/bash

killall dunst &

killall compton &

killall udiskie &

bspc monitor -d 1 2 3 4 5

bspc config split_ratio             0.5
bspc config borderless_monocle   	false
bspc config gapless_monocle      	false
bspc config focused_border_color    \#bf00f6
bspc config active_border_color		\#bf00f6
bspc config normal_border_color	    \#145cff
bspc config presel_feedback_color	\#bf00f6
bspc config focus_follows_pointer   true
bspc config border_width            2
bspc config window_gap              4
bspc config focus_follows_pointer   true
bspc config center_pseudo_tiled     true
bspc config single_monocle			true

#State configuration
bspc rule -a Uget-gtk state=floating
bspc rule -a MEGAsync state=floating
bspc rule -a Gthumb state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a qt5ct state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Timeshift-gtk state=floating
bspc rule -a Grub-customizer state=floating
bspc rule -a Guake state=floating
bspc rule -a Xarchiver state=pseudo_tiled
bspc rule -a Eog state=floating
bspc rule -a "Kvantum Manager" state=floating
bspc rule -a Gnome-disks state=floating
bspc rule -a Gpick state=floating
bspc rule -a Dconf-editor state=floating
bspc rule -a Lightdm-settings state=floating


bspc config external_rules_command  ~/.config/bspwm/external_rules.sh

~/.config/polybar/launch.sh &

sleep 1 & 

feh --bg-fill ~/.config/wallpaper/7pm.jpg &

compton -b &

dunst &

uget-gtk &

uget-integrator-firefox &

uget-integrator &

megasync &

udiskie --smart-tray &

greenclip daemon &

xidlehook --not-when-fullscreen --not-when-audio --timer normal 900 'betterlockscreen -l blur' '' &

xidlehook --timer normal 3600 'betterlockscreen -s blur' '' &

#nm-applet &
