#! /bin/bash

~/.config/polybar/scripts/workspaces.sh &

sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config split_ratio             0.5
bspc config borderless_monocle   	false
bspc config gapless_monocle      	false
bspc config focused_border_color    \#bf00f6
bspc config normal_border_color	    \#145cff
bspc config presel_feedback_color \#bf00f6
bspc config focus_follows_pointer   true
bspc config border_width            3
bspc config window_gap              4
bspc config focus_follows_pointer   true
bspc config center_pseudo_tiled     true
bspc config single_monocle			true

#Outer gaps
bspc config top_padding 29
bspc config left_padding 20
bspc config bottom_padding 20
bspc config right_padding 20

~/.config/polybar/launch.sh &

