#! /bin/bash

#Outer gaps
#Set override-redirect=true in polybar config
#Tell the Window Manager not to configure the window.
#Use this to detach the bar if your WM is locking its size/position.
#Note: With this most WMs will no longer reserve space for the bar and it will overlap other windows. You need to configureyour WM to add a gap where the bar will be placed.
bspc config top_padding 52 #Amount is bar-margin/y-offset+bar-height+desired-value
bspc config left_padding 20
bspc config bottom_padding 20
bspc config right_padding 20

~/.config/polybar/launch.sh &

