#! /bin/bash

#Outer gaps
bspc config top_padding 53 #Amount is bar-margin+bar-height+window-gap+desired-value
bspc config left_padding 20
bspc config bottom_padding 20
bspc config right_padding 20

~/.config/polybar/launch.sh &

